version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=yadavv4
      - POSTGRES_USER=postgres
      - POSTGRES_DB=simple_blog_api
  api:
    depends_on:
      - postgres
    image: yadavv4/simple_blog_api_new
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yadavv4
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432